### PR TITLE
Clean gh pages

### PR DESCRIPTION
**Pull request by ovbutt**

### CODE REVIEW

**Comment by ovbutt** [comment]
@shah kindly merge this PR so I can test the deployment.

**Comment by shah** [comment]
I've merged the PR @ovbutt please continue to test.

**Comment by ovbutt** [comment]
Perfect thanks @shah I have tested it is working fine now. You can also test it here.
https://netspective-labs.github.io/sql-aide/

**Comment by shah** [comment]
Looks good @ovbutt I added that link to the README.md and GitHub repo summary. I also created ticket for you with some errors to correct.

**Pull request merged**
